### ISSUE TITLE
New API endpoint routing

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueDatabaseService#39]
**Is your feature request related to a problem? 
Current Endpoint is using single route and multiple parameters for league, model type and id. This works well for the app but makes it hard to use for other people.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SSchulze1989** [comment]
# Tasks
- [ ] ~~Implemement type detection from shortnames. Best would be to use a dictionary that is filled at startup using reflection.~~
- [x] Implement endpoint routing on existing controller or create new controller
- [ ] Change DTO type names: Remove "DataDTO" and "DTO" ending for less complexity. Differentiation between "Model" and "Entity" is already done with the right endings.
