### ISSUE TITLE
Implement automated Result calculation

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueDatabaseService#46]
**Is your feature request related to a problem? Please describe.**
Currently, the user has to click "Calculate" everytime he wants to have changes calculated on the results.

**Describe the solution you'd like**
Implement a check on the server that marks the result as "need to be recalculated".
When the result is loaded and is marked, the calculation is performed beforehand.

**Related Issues**
SSchulze1989/iRLeagueManager#85

**Comment by SSchulze1989** [comment]
## Tasks
- [ ] Implement check for:
  - [x] Results upload
  - [x] Settings changed 
  - [x] Review Results changed
  - [x] Custom penalty added/changed
  - [x] Custom penalty deleted
  - [x] Filters changed
- [x] Implement loading when marked
